#!/usr/bin/perl -w

use strict;
use warnings;
use Switch;
use Data::Dumper;
use NagiosStatus;

my $boxsize="20px";
my $statusfile="/var/spool/icinga/status.dat";
my $target_url="/icinga/cgi-bin/extinfo.cgi";
my $refresh=5*60; #5 minutes

my $status_object = NagiosStatus->new($statusfile);
$status_object->parse_statusfile();
$status_object->evaluate();

print <<"EOF"
Content-Type: text/html; charset=ISO-8859-1

<html>
    <head>
        <meta http-equiv='refresh' content='$refresh'>
        <style type="text/css">
            .box {
                margin:1px 1px 0px 0px;
                width:$boxsize;
                height:$boxsize;
                display:inline-block;
            }
        </style>
    </head>
<body>
EOF
;

print "<h1>Host Info</h1>\n";
foreach my $host ( keys %{ $status_object->{'HOSTS'}}) {
    my $current_state=$status_object->{'HOSTS'}->{$host}->{'current_state'} ;
    $host=~s/ /+/g;
    my $color="#ffffff";
    switch ($current_state){
        case(0) { $color = "green";  }
        case(1) { $color = "yellow"; }
        case(2) { $color = "red";    }
        else    { $color = "purple"; }
    }
    print "<a href='$target_url?type=1&host=$host'><div class='box' style='background-color:$color' title='$host'></div></a>";
}

print "<h1>Service Info</h1>\n";
foreach my $servicekey ( keys %{ $status_object->{'SERVICES'}}) {
    my $current_state=$status_object->{'SERVICES'}->{$servicekey}->{'current_state'};
    $servicekey=~s/ /+/g;
    my ($host,$service)=split /_/,$servicekey;
    my $color="#ffffff";
    switch ($current_state){
        case(0) { $color = "green";  }
        case(1) { $color = "yellow"; }
        case(2) { $color = "red";    }
        else    { $color = "purple"; }
    }
    print "<a href='$target_url?type=2&host=$host&service=$service'><div class='box' style='background-color:$color' title='$host $service'></div></a>";
}

print "</body>\n</html>\n";
